### ISSUE TITLE
Test the `serde` feature together with the `alloc` feature

### ISSUE THREAD

**Issue by brycx** [orion-rs/orion#220]
~~Awaiting #193~~

Having both `serde` and `alloc` enabled should work. Unless `serde` is only used in high-level, because `alloc` is only meant to be used for `no_std`-enabled Argon2i. In that case, it seems to make little sense to expect a user to use both at the same time.

**Comment by vlmutolo** [comment]
So this is an interesting question. I guess the heart of it is whether it ever makes sense to enable Orion's alloc feature without enabling serde's. After briefly looking at [serde's documentation](https://serde.rs/feature-flags.html), it seems like the relevant part for us is that serde's `alloc` feature enables serialization of the normal container formats like `Vec` and `String`. 

So… if a user is doing some kind of `no_std` work, and then opts into the `alloc` feature to use `argon2i`, and then also opts into Orion's `serde` feature flag… I guess it seems like they would *also* want (need?) to have serde's `alloc` feature enabled, since the `PasswordHash` serialization definitely depends on `String`s. 

I think that makes sense. Maybe.

**Comment by brycx** [comment]
I see what you mean, but in terms of `argon2i` only the `hazardous` implementation is enabled through `alloc`. The `safe_api` feature of course also enables it, but the `PasswordHash` is only used in the high-level API, which requires `safe_api`.

OTOH, the `serde` impls are also defined for `hazardous`-types, such as those from `construct_public!`. Then we'd be taking a scenario were the users use the `alloc + serde` feature to get `serde` support on `no_std`.

It does seem like, right now, `serde` should use its `alloc` feature, if Orion has `alloc` set as well. I think we agree on that?

**Comment by vlmutolo** [comment]
So I've been thinking about it a bit more. 

The serde implementation currently uses `Vec` for pretty much every `Deserialize` impl. I think this means that, in its current form, it *needs* to have serde's `alloc` feature enabled.

In the future, we may want to try to write non-allocating versions of `Deserialize`. That's something I can look into. But for now I think that Orion's `serde` feature should imply serde's `alloc` feature.

**Comment by brycx** [comment]
Yes, this sounds like the correct approach. If Orion is alloc, then so is serde. If Orion has serde, but no alloc, then it would be expected that safe_api is enabled.
